---
development:
  cloud_name: brazada
  api_key: '739593615393383'
  api_secret: 73fkye5lFZ2RA92_0wRREwkVmoY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: brazada
  api_key: '739593615393383'
  api_secret: 73fkye5lFZ2RA92_0wRREwkVmoY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: brazada
  api_key: '739593615393383'
  api_secret: 73fkye5lFZ2RA92_0wRREwkVmoY
  enhance_image_tag: true
  static_image_support: false
